### ISSUE TITLE
remove content-length  check

### ISSUE THREAD

**Issue by NoumanSaleem** [jshttp/type-is#32]
Firstly, thanks for all the great libraries on `jshttp`!

The readme states

> Infer the content-type of a request.

However, because `typeofrequest()` is [always checking content-length](https://github.com/jshttp/type-is/blob/master/index.js#L127), the application of this package is limited. This makes sense given the primary user is `body-parser`, however it would be great for the package to be more generic.

**Comment by dougwilson** [comment]
Sure, but maybe I can better understand your use-case. The function you're referring to is to check the type of a request, and the HTTP specification defines how to validate if a request actually has an entity which is what the Content-Type header references. If there is no entity, then the Content-Type header is supposed to be ignored, so we're just following the HTTP specification here.

There may be another solution we can provide, though. Can you help understand what you're trying to do, perhaps provide a runnable example that you're expecting to pass the check but fails because of this?

**Comment by NoumanSaleem** [comment]
@dougwilson for instance, to guard a router (collection of GET and POSTs) by only accepting `content-type:application/json` to minimize CSRF risk from http forms.

**Comment by dougwilson** [comment]
Hi @NoumanSaleem hm, I'm not sure I understand completely. Is it possible you can provide a runnable example that you're expecting to pass the check but fails because of this? Or maybe try explaining in a different way, not sure. The solution is defiantly not going to be to just remove that check, because it's layed out in the HTTP specification, and we follow that instead of making up our own rules :) There may be a good solution we can come up for your use-case, but ideally we need to understand it well to determine what we can help do for you 👍 

At the bare minimum, the `typeis.is` method is exactly the same as `typeis`, but doesn't do the length check, since the first argument is the type instead of a request. Not sure if that helps you or not, but just in case you didn't see that method in the docs.
