### ISSUE TITLE
Cannot deal with the content-type with semicolon

### ISSUE THREAD

**Issue by h2012c106** [jshttp/type-is#34]
Some websites may return the headers with content-type 'text/html;', I think it should be treated as legal html as well.

code:
```
let typeis = require('type-is').is;

let val = 'text/html;';
let types = ['html', 'xhtml', 'text/xml', 'application/xml', '+xml'];

console.log(typeis(val, types)); // false
```

**Comment by dougwilson** [comment]
Yes, this is intended. That type is invalid, because a semicolon signals the start of a new parameter and none is there. For all we know it was accidentally truncated. If you would like to support anyway, just trim the down before passing it to the library if you don't want validation to look at parameters.
