### ISSUE TITLE
Invalid result for some multipart/formdata requests

### ISSUE THREAD

**Issue by bitkomponist** [jshttp/type-is#49]
some browsers use `multipart/form-data` boundaries encapsulated by `===`. According to [spec](https://www.w3.org/Protocols/rfc1341/7_2_Multipart.html), this is valid. however `type-is` fails here:

```javascript
const {is} = require('type-is');

console.log(is({headers:{'content-type':'multipart/form-data; boundary====1626687228335==='}},['multipart']));
console.log(is({headers:{'content-type':'multipart/form-data; boundary=--------------------------575525763331173399582839'}},['multipart']));
```

expected result would be:
```
multipart
multipart
```
actual result is:
```
false
multipart
```

**Comment by dougwilson** [comment]
Hello, and thanks for the report. A boundary with equal signs is certainly valid, but the issue here is the content-type header you provided is invalid. You can find the syntax for the content-type header defined in the HTTP RFC 7231. The issue with the header you provided is that a parameter value cannot have an equal sign without it being quoted, like so:
```js
console.log(is({headers:{'content-type':'multipart/form-data; boundary="===1626687228335==="'}},['multipart'])
```

It would seem this is a bug on the user agent side. What is the exact user-agent header of the web browser that is generating such a header?

**Comment by bitkomponist** [comment]
Thanks for your reply, i didn't notice that quotation part of the spec, thanks for elaborating! in our case the request came from a clients browser, but sounds to me there that there must be some proprietary middleware involded which strips the quoting! thanks for the help 👍
